CREATE DATABASE DBCons;
USE DBCons;

CREATE TABLE Autos(

id INT IDENTITY(10,5) PRIMARY KEY,
marca VARCHAR(50) NOT NULL DEFAULT 'Sin marca' ,
fecha_creacion DATETIME NOT NULL DEFAULT CURRENT_TIMESTAMP

);

CREATE TABLE Comprador(

id INT IDENTITY(100,10) PRIMARY KEY,
id_auto INT NOT NULL,
nombre VARCHAR(50) NOT NULL DEFAULT 'Sin nombre',
apellidos VARCHAR(100) NOT NULL DEFAULT 'Sin apellido',
nacimiento BIGINT NOT NULL DEFAULT 0,
fecha_registro DATETIME NOT NULL DEFAULT CURRENT_TIMESTAMP
FOREIGN KEY (id_auto) REFERENCES Autos(id)

);

SELECT * FROM Autos;
SELECT * FROM Comprador;

